### PR TITLE
[WIP] Move assign_remaining_args function to allow reuse

### PR DESCRIPTION
**Pull request by JCodyA**
Move function to options.py to allow general reuse as mentioned in issue #7347 

Closes:  #7347 
Signed-off-by: J. Cody Arnholt <j.cody.tbone@gmail.com>

### CODE REVIEW

**Comment by JCodyA** [comment]
This is a first step and I opened this pr now to allow guidance and comment.

**Comment by behrisch** [comment]
Now you need to call the function from its new location in duaIterate.py to retain the old behavior

**Comment by JCodyA** [comment]
So should I just add ```from sumolib.options import assign_remaining_args``` to the import section of duaIterate.py?  Sorry I just wanted to check first.  I thought the ```import sumolib``` line covered it.  This is a learning experience for me as well to be honest.

**Comment by behrisch** [comment]
You can just add it to the existing line https://github.com/eclipse/sumo/blob/44f333bcc8f234b73de99b1cfc1e547ef926b293/tools/assign/duaIterate.py#L39 with a comma.

**Comment by JCodyA** [comment]
Sounds good.  I'll do that, and the same with https://github.com/eclipse/sumo/blob/44f333bcc8f234b73de99b1cfc1e547ef926b293/tools/assign/duaIterate.py#L26-L27
so that it becomes ```from __future__ import print_function, absolute_import```  If everything checks out I can squash my commits into one if that is the preferred method here.

**Comment by behrisch** [comment]
Please don't mix in unrelated refactoring changes.

**Comment by behrisch** [comment]
I just noticed that get_long_option_names is just used in the moved function so there is no need to import it.

**Comment by JCodyA** [comment]
Looks like everything is passing now.  I can go ahead and squash everything into one commit if you like.  Is there a tag or anything I should put in the commit comment body like [skip ci] so that it doesn't do all the tests again and waste processing?  Thanks for your help by the way, this has been a learning experience for me.

**Comment by behrisch** [comment]
Well, this was only the first step, now we need to actually use that function in randomTrips.py.

**Comment by JCodyA** [comment]
I'm looking through randomTrips.py now and trying to figure it out.  I feel that I have a learning curve here but I will keep working.  Any guidance is definitely appreciated.

**Comment by behrisch** [comment]
The next step is probably to assign the remaining args in randomTrips.get_options to options.remaining_args and then pass them to the function you just moved. (The best way would be probably to refactor randomTrips to use the new argParser instead of the old OptionParser but that is maybe too much for now.)

**Comment by JCodyA** [comment]
Ok, this is making more sense once again.  Would you like me to try and do the refactor?

**Comment by behrisch** [comment]
Only if you are familiar with optParse and argParse and the differences. Otherwise just assign the parsed args to options.remaining_args.

**Comment by behrisch** [comment]
@JCodyA Are you still working on this?

**Comment by JCodyA** [comment]
I haven't since we last connected here.  Life has intervened a little.  I'm happy to continue but I still have to prioritize my time

**Comment by behrisch** [comment]
Thanks for getting back so fast. I don't want to add stress just wanted to check whether you need help.

**Comment by JCodyA** [comment]
Thank you!  No stress added whatsoever, and I will need help if I remember right but I'll need to look over everything again and refresh myself.

**Pull request closed without merging**
