### PR TITLE
Add findRoute function

### PR DESCRIPTION
**Pull request by pcg76**
Add findRoute function
Specify a timeout to prevent SUMO from freezing

Signed-off-by: CG <timpcg76@yahoo.com.sg>

### CODE REVIEW

**Comment by behrisch** [comment]
Thanks for the pull request! Please try to keep different things in different PRs. I already added your setMaxSpeed-fix now, so please either do a new PR which contains only the new findRoute function or if it is too cumbersome gve me a note and I add it by hand.

**Comment by pcg76** [comment]
Thanks! I’m new to pull request and I thought I added a new pull request for my setMaxSpeed fix. I will try to do a new PR for the findRoute function.

**Comment by pcg76** [comment]
@behrisch I have difficulty creating another PR without the commits. Is it possible to add it by hand? Thanks!

**Comment by behrisch** [comment]
If the timeout issue is still of importance please open a new ticket (or PR) for that. The major part of findroute is now in the master.

**Pull request closed without merging**
