### PR TITLE
Replace null and 0 with nullptr

### PR DESCRIPTION
**Pull request by seb-ehm**
Where appropriate, this commit replaces all occurrences of 0 or NULL
with nullptr.

Signed-off-by: Sebastian Ehmann <sebastian@dipolmoment.de>

### CODE REVIEW

**Comment by behrisch** [comment]
Thanks for the new patch. Could you please try to resolve the new conflicts? I will try to merge then ASAP.

**Comment by seb-ehm** [comment]
The branch should be ready to be merged now.

**Comment by behrisch** [comment]
Thanks a lot!

**Comment by behrisch** [comment]
@seb-ehm  We want to add GPLv2+ as a secondary license to sumo and need your permission to also include this (and maybe code from other pull requests) in this license change. If you agree please add a +1 to #6506. This ticket also has more details and if you have questions you can ask them there. Thank you in advance!

**Pull request merged**
