### PR TITLE
Update EIDM

### PR DESCRIPTION
**Pull request by Domsall**
Updates following open issues and netedit support

Refactored SlowtoStart-Function

### CODE REVIEW

**Comment by namdre** [comment]
various test cases involving EIDM are failing now. Please confirm that their new behavior is expected.

**Comment by Domsall** [comment]
thanks for your review. I just checked all tests and yes, the new behavior is expected.

Shall I run the tests on my Windows machine and push the results?!
What we also could do: Change the sigma-parameters to 0. Future tests should then run independent of the OS.

**Comment by namdre** [comment]
If the feature under test doesn't require sigma, then I recommend setting it to 0.  We also do this for many of our tests.
Go ahead and push the expected test results afterwards.

**Comment by Domsall** [comment]
A review would be great, as I am updating tests for the first time.

**Comment by namdre** [comment]
looks fine to me

**Pull request merged**
