### PR TITLE
Add traci gui variable for checking view presence

### PR DESCRIPTION
**Pull request by mightyCelu**
This patch introduces a new traci check for testing existance of a view. This was previously not possible and could not be distinguished from unimplemented traci methods.

### CODE REVIEW

**Comment by behrisch** [comment]
Thank you for the contribution!
Could you please create an Eclipse account and fill out the ECA form as described here: http://sumo.dlr.de/wiki/FAQ#How_do_code_contributions_work.3F Also please add a signed off to your commit.

**Comment by namdre** [comment]
Sorry for the IP-validation annoyance. Can we do anything to help you with this?

**Comment by mightyCelu** [comment]
I had some trouble completing the process as I used a shortened domain in the email adress of the ECA, even though I used the long version on my GPG key. I had to wait for the ECA to be revoked before being able to submit a new one.

I hope this passes the ip-validation now.

**Comment by behrisch** [comment]
The checks pass now but the python implementation looks faulty (refers to the wrong variable). Could you please fix that? Thanks.

**Comment by behrisch** [comment]
It still shows the old version here.

**Comment by mightyCelu** [comment]
My bad, pushed it again.

**Comment by behrisch** [comment]
Thanks a lot!

**Pull request merged**
