### PR TITLE
fix for implausibleRoute.py #12069 

### PR DESCRIPTION
**Pull request by aminissn**
added additional-files for vehucle type definition, unsorted-input and irgnore-errors for duarouter support to implausibleRoute.py

### CODE REVIEW

**Comment by namdre** [comment]
Thanks! In order for me to merge the PR directly, I'm afraid you have click through the ECA (https://sumo.dlr.de/docs/FAQ.html#how_do_code_contributions_work).

**Comment by aminissn** [comment]
> Thanks! In order for me to merge the PR directly, I'm afraid you have click through the ECA (https://sumo.dlr.de/docs/FAQ.html#how_do_code_contributions_work).

I think I pushed my change and committed the pull request, but since this is my first contribution on GitHub, someone must approve my request? not sure if I did everything correctly:-/

**Comment by namdre** [comment]
One of the checks failed:  `eca - The author(s) of the pull request is not covered by necessary legal agreements`.
Probably you didn't register an eclipse account under the email address that was used for this commit.

**Comment by aminissn** [comment]
I just logged in to my eclipse account (same Email as my GiHub) and updated the ECA and revalidated the check here, but the eca check still fails. Maybe it needs some time to update?

**Comment by m-kro** [comment]
Commits have also to be signed (see [docs](https://sumo.dlr.de/docs/FAQ.html#how_do_code_contributions_work)).

**Comment by namdre** [comment]
The eclipse validation page still says `Anonymous (30176885+aminissn@****.****.****.com)`

**Comment by aminissn** [comment]
I will close this request and redo it from scratch by forking to the sumo project. I hope I can do it correct this time, so I can contribute more often in the future.

**Pull request closed without merging**
