### PR TITLE
New Parameter CalcReason for stop/free/followSpeed

### LINKED ISSUE #11461: EIDM: emergency braking when approaching stop
same test as as #11361,
happens on average once per simulation

quick replication with seed 38

most likely related to the new stop approach code from #11460

### PR DESCRIPTION
**Pull request by Domsall**
Parameter indicates what the reason for the call is and what the return speed will be used for.

Fixes #11461 and #11265

`CalcReason` was the best name I could come up with... feel free to change it :)

adaptToJunctionLeader-Code has changed a bit, but this does not change any procedure.
The new function looks like it has duplicate calls, but they differ slightly. The Code changes even result in a lower amount of stopSpeed calls.

### CODE REVIEW

**Comment by Domsall** [comment]
Two tests were failing, updated values:

- IDM test with driverstate-device: The changed followSpeed-calls in `insertionFollowSpeed` already result in a saved "myLastPerceivedSpeedDifference"-value that is used in future calculations. If that is not wished, `pred` needs to be `nullptr`.
- FCD Output with CACC-model: In the first call (to check for insertion), caccVehicleMode is not set yet.

**Comment by namdre** [comment]
1. why does `maximumSafeFollowSpeed` need a `usage` parameter? It's not virtual and should not be of concern to an cfmodel implementation.

2. can the changes in `adaptToJunctionLeader` go into a separate pull request? Everything else I understand (and it should basically have no impact on anything except for EIDM). - Having no tests except EIDM tests change would be a good sanity check here for me.

 The changes `adaptToJunctionLeader` I don't undestand (yet) and I'd like to have a detailed look at their impacts in isolation.

**Comment by Domsall** [comment]
1. You added `gComputeLC=true` in #11106. `maximumSafeFollowSpeed` uses `gComputeLC` and may get called by some models in `followSpeed`. For the same output, I needed to add the `usage` parameter to `maximumSafeFollowSpeed` to make the Code work the same way as with `gComputeLC` at this point.

2. The changes to `adaptToJunctionLeader` do not change anything for other models (no tests changed and the "logics" of the Code (should) have stayed the same).

I do not know any way to "easily" undo this. Do you have an idea? The changes are in [dbc23c5](https://github.com/eclipse/sumo/pull/11560/commits/dbc23c5af05246a980ec59d4efc9721d57297e32)

**Comment by namdre** [comment]
1. The gComputeLC in MSVEhicle was only a quick fix and you already removed the lines (as I intended). Since there is nothing in maximumSafeFollowSpeed that reacts to the 'usage' parameter, you can safely remove it.
2. simply add another commit that reverts this particular change. Then I can squash the PR and it will be gone.

**Comment by Domsall** [comment]
1. `usage` is used in `maximumSafeFollowSpeed` in the same way as `MSGlobals::gComputeLC`?! If I leave out `usage`, tests change. That is why I replaced `MSGlobals::gComputeLC` with `usage`.
2. Ok, I will do this. I will then also update the EIDM-tests.

**Comment by Domsall** [comment]
Done

**Comment by namdre** [comment]
> usage is used in maximumSafeFollowSpeed in the same way as MSGlobals::gComputeLC?! If I leave out usage, tests change. That is why I replaced MSGlobals::gComputeLC with usage.

- As I tried to explain earlier, gComputeLC will remain in the code since it is used in other parts that are not related to carFollowing (i.e. MSLink). 
- also, getMaximumSafeFollowSpeed is not virtual, hence no custom carFollowingModel will need to touch this
- since getMaximumSafeFollowSpeed was working fine with using gComputeLC it can continue to use this and doesn't need to be changed
- the changed CACC test (output/fcd-output/params_caccVehicleMode) is due to setting a parameter conditional on the 'usage' parameter directly in the model. I think this one is ok
- changed IDM test (devices/driverstate/queue_stop_start_idm) is due to supplying the 'pred'  object as new argument in `insertionFollowSpeed` since this influences the driver state
- taking out usage from 'getMaximumSafeFollowSpeed' has no effect on tests

I've added debug code to `getMaximumSafeFollowSpeed` and confirmed that the 'usage' branch is never triggered

```
if (gap < 0 && !MSGlobals::gComputeLC && usage != CalcReason::CURRENT) {
        std::cout << SIMTIME << " debug usage=" << usage << "\n";
    }
```

**Comment by Domsall** [comment]
I had a bug in my Code and just fixed it, sorryfor the confusion!

When you delete `usage` from `MSCFModel::maximumSafeFollowSpeed`, test bugs/8xxx/ticket8817 changes.
If these changes are intended, I will undo the Code parts.

Again, sorry for all the additional work. I thought you added `gComputeLC` in your quick fix not only for the EIDM, but also for followSpeed->maximumSafeFollowSpeed (which also uses `gComputeLC`).

**Comment by namdre** [comment]
I still cannot reproduce the changing behavior in bugs/8xxx/ticket8817 when applying the current diff of this PR and removing/keeping the usage in maximumSafeFollowSpeed. 
(I'm switching between the lines
```
 if (gap >= 0 || MSGlobals::gComputeLC || usage != CalcReason::CURRENT) {
```
and
```
if (gap >= 0 || MSGlobals::gComputeLC) {
```
)

The reason why gComputeLC is used in `maximumSafeFollowSpeed` is because negative gaps have different semantic when considering a leader on the current lane and a leader on a neighboring lane. This is unrelated to the CURRENT and CURRENT_WAIT semantic.  (So please just keep maximumSafeFollowSpeed as it was).

Also, the missing onInsertion parameter bug that you fixed in 6eaf3be is still present in the ACC and CACC models for this PR.

**Comment by Domsall** [comment]
Sorry for the back and forth.
I left the ticket8817-test outdated (which was the reason for the changes). Please update after merging.

**Comment by namdre** [comment]
I was finally able to see the failing test (not sure why I couldn't before). The new behavior is correct and the previous behavior was an unintended side effect of my quick fix (`/// @fixme: setting gComputeLC is workaround until implementing #11265`)

Now I understand why you thought that the new flag was needed in maximumSafeFollowSpeed. ... 
It's fine now (-:

**Pull request merged**
