### PR TITLE
vClass-specific speeds in the lane parameter dialog of SUMO-GUI (ref #11100)

### PR DESCRIPTION
**Pull request by vijay-jaisankar**
ref: https://github.com/eclipse/sumo/issues/11100

In this PR, the following functionalities have been added:
- Showing vClass specific speeds in the dialog box
- Changing `maxspeed` to `allowed speed`

### CODE REVIEW

**Comment by behrisch** [comment]
Thank you! Please use the new c++ loop style `for (const auto& elem : map)` and do not make an unnecessary copy of the map (store it as a reference or do not store it at all). Also please change maxspeed to allowed speed for the existing entry as well

**Comment by vijay-jaisankar** [comment]
Sure thing, will update the PR soon.

**Comment by vijay-jaisankar** [comment]
These commits should fix the issue, please check.

**Comment by vijay-jaisankar** [comment]
Thanks, I'll use this code formatting for the next PRs :)

**Comment by vijay-jaisankar** [comment]
I've since validated my ECA status.

**Pull request merged**
