### PR TITLE
Adjusted sumo --fcd-output to output both m x/y and lat/lon along wit…

### PR DESCRIPTION
**Pull request by romleiaj**
…h angle of car to calculate correct bbox.

### CODE REVIEW

**Comment by romleiaj** [comment]
My apologies, this was for a personal, specific use case where I needed both meter x/y and lat/lon in the same output, and trimmed out the other outputs as I did not need them, and I had no intentions of merging this with the central repo and closed as soon as possible. Feel free to delete. I am still new to Git and learning much. 
Awesome tool, however. The ability to customize is remarkable. Thanks for all your hard work and speedy review.

**Comment by namdre** [comment]
Very well.

**Comment by passengerxuhongli** [comment]
hello, there is a question that is confusing me:
     that is  when i used the option "--fcd-output" to output,  the result is same as using the option "--fcd-output.geo". 
 both of those location is meter x/y, but i want a geo-coordinates lat/lon .
  can you help me ? thank you very much!
the commend i used is listed as following:
  "sumo-gui.exe -c wujinqunew.sumo.cfg --fcd-output fcdData"
  "sumo-gui.exe -c wujinqunew.sumo.cfg --fcd-output.geo true --fcd-output fcdData"

**Comment by passengerxuhongli** [comment]
thanks, i checked  output files again. i found you are right! it dose work in deed. sorry for my stuipy question! and thank you again!

**Pull request closed without merging**
