### PR TITLE
Modification of DuaIterate.py 

### PR DESCRIPTION
**Pull request by bmbamdad**
1- Add Methods of Sussessive Average for the Swapping algorithm; 
2- Change the name of --convergence-steps to PSwap; 
3- Modification of marginal cost calculation

Signed-off-by: Behzad Bamdad Mehrabani <bm.bamdad@gmail.com>

### CODE REVIEW

**Comment by namdre** [comment]
Three tests change their results with this commit:

```
2022-08-23 11:02:29,699 - S: TOOLS.ci test-case assign/dua-iterate/braess/shortcut_logit FAILED on fv-az39-938 : missing results for dualog,tripinfos, differences in errors,output
2022-08-23 11:02:39,127 - S: TOOLS.ci test-case assign/dua-iterate/braess/shortcut_gawron_marginal FAILED on fv-az39-938 : differences in dualog,tripinfos
2022-08-23 11:02:41,176 - S: TOOLS.ci test-case assign/dua-iterate/braess/shortcut_gawron_marginal_default FAILED on fv-az39-938 : differences in dualog,tripinfos
```
Did you check whether the new results make sense and should be accepted?
I'm against changing the option name because it breaks backward compatibility (this is responsible for the change in `shortcut_logit` since it does not use marginal costs.
You could introduce a synonym for the option or simply change the wording of the option help to include `PSwap`.

**Comment by bmbamdad** [comment]
As long as these changes are due to marginal cost calculations, they are acceptable. Also, instead of renaming "convergence steps", I modified the help of this option.

**Comment by bmbamdad** [comment]
Now I also add duaIterateMix.py:  

# duaIterateMix
A Multiclass simulation-based traffic assignment model for mixed traffic flow of connected and autonomous vehicles and human-driven vehicles. 

duaIterateMix.py is a traffic assignment tool that helps you to solve the traffic assignment problem in the mix traffic condition (mix flow of Connected and Autonomous Vehicles (CAVs) and Human Driven Vehicles (HDVs)). This tool is based on the duaIterate.py. 
It is assumed that HDVs follow user equilibrium and CAVs follow system optimal.  

Warning: 
HDVs travel demand file should be inserted by "-t" option and must be named as "trips.trips.xml"
CAVs travel demand file should be inserted by "-r" option and must be named as "trips.trips.CAV.xml"

For More info on this tool, please visit:  https://github.com/bmbamdad/duaIterateMix

**Comment by namdre** [comment]
Sorry for my late response. The changes to duaIterate are fine and I'd merge them. 

With regard to duaIterateMix.py I have the following suggestions
- please do a separate pull-request (so I can already merge the changes to duaIterate.py)
- please do not employ hard-coded file names. Instead provide options that allow setting these file names
- please provide at least a single test case for the new tool (it's ok if you simply attach the files as a zip if you don't wish to deal with texttest) However, the files should have a size/simplicity level that matches those of the existing tests -
- please re-use functionality of the existing tools to avoid redundancy (i.e. as done by cadytsIterate.py)

**Pull request closed without merging**
