### PR TITLE
Parking Lot Position in Parking Area

### PR DESCRIPTION
**Pull request by Domsall**
Changed the Position of Parking Lots in Parking Area, as these were located on the road at angles between 180° and 360°

### CODE REVIEW

**Comment by namdre** [comment]
Thanks for the contribution.
Can you please check whether your github account is already covered by the contributor license agreement? The current check is failing. (see https://sumo.dlr.de/docs/FAQ.html#how_do_code_contributions_work)

**Comment by namdre** [comment]
> Thanks for the contribution.
> Can you please check whether your github account is already covered by the contributor license agreement? The current check is failing. (see https://sumo.dlr.de/docs/FAQ.html#how_do_code_contributions_work)


Nevermind. All checks are passing now.

I welcome your idea of interpreting angles above 180 degrees in a more useful manner. However I have two concerns with the current PR:
- your version shifts the point of rotation closer to the road. This makes the shape intersection with the road space when at an angle (left is old version, right is your version)
Screenshot from 2020-07-02 14-07-49
- at large angles there is a shift away from the parkingArea:
Screenshot from 2020-07-02 14-09-20

**Comment by Domsall** [comment]
I have changed the Code again and am getting better results now. I don't know what the best procedure is, so I'll just leave the changes here for now:

```
if (myAngle >= 0 && myAngle <= 90) {
    pos.setx((f.x() + s.x())/2 - (myWidth / 2)*(1-cos(myAngle / 180 * M_PI))*cos(hlp_angle / 180 * M_PI));
    pos.sety((f.y() + s.y())/2 + (myWidth / 2)*(1-cos(myAngle / 180 * M_PI))*sin(hlp_angle / 180 * M_PI));
    pos.setz((f.z() + s.z())/2);
} else if (myAngle > 90 && myAngle <= 180) {
    pos.setx((f.x() + s.x())/2 - (myWidth / 2)*(1+cos(myAngle / 180 * M_PI))*cos(hlp_angle / 180 * M_PI));
    pos.sety((f.y() + s.y())/2 + (myWidth / 2)*(1+cos(myAngle / 180 * M_PI))*sin(hlp_angle / 180 * M_PI));
    pos.setz((f.z() + s.z())/2);
} else if (myAngle > 180 && myAngle <= 270) {
    pos.setx((f.x() + s.x())/2 - (myLength)*sin((myAngle - hlp_angle) / 180 * M_PI) - (myWidth / 2)*(1 + cos(myAngle / 180 * M_PI))*cos(hlp_angle / 180 * M_PI));
    pos.sety((f.y() + s.y())/2 + (myLength)*cos((myAngle - hlp_angle) / 180 * M_PI) + (myWidth / 2)*(1 + cos(myAngle / 180 * M_PI))*sin(hlp_angle / 180 * M_PI));
    pos.setz((f.z() + s.z())/2);
} else if (myAngle > 270 && myAngle < 360) {
    pos.setx((f.x() + s.x())/2 - (myLength)*sin((myAngle - hlp_angle) / 180 * M_PI) - (myWidth / 2)*(1 - cos(myAngle / 180 * M_PI))*cos(hlp_angle / 180 * M_PI));
    pos.sety((f.y() + s.y())/2 + (myLength)*cos((myAngle - hlp_angle) / 180 * M_PI) + (myWidth / 2)*(1 - cos(myAngle / 180 * M_PI))*sin(hlp_angle / 180 * M_PI));
    pos.setz((f.z() + s.z())/2);
} else {
    pos = (f + s)*0.5;
}
```

Regarding the first issue: I wanted to have the vehicles park near the road and not `width/2` away from it. With the changes, the Parking Lots shouldn't be on the road anymore.
The shifting at large angles should also not occur anymore, as between 180° and 360° the Parking Lot is now pushed onto the Parking Area, not slided. I think this is the intended manner, although now, one can't differentiate between a 185° and 5° Parking Lot anymore until a car parks there.

**Comment by namdre** [comment]
Looks very nice now. Thanks for the contribution!

**Pull request closed without merging**
