### PR TITLE
Documentation fixes and added direct download links. 

### PR DESCRIPTION
**Pull request by sunn-e**
Thanks for the guidance about ECA @namdre  I hope I am doing this correct.
You may refer to #5764 for further comments.

Signed-off-by: Sunny Dhoke <sunnydhoke22@gmail.com>

### CODE REVIEW

**Comment by sunn-e** [comment]
Still ECA failed? What am I doing wrong?

**Comment by namdre** [comment]
The 'updating readme' commit seems to be fine.
However, the other two merge commits are failing validation. This time Eclipse doesn't say why and just splits out `This validation request is closed or unavailable.`
I'm just guessing at this point but it might help to redo the contribution as a single commit from a freshly forked repo.

**Comment by behrisch** [comment]
I like the repo size badge but I don't like the reformatting. What is the reason to do so? Especially adding the backtick formatting for the command seems to increase indentation and makes it harder to read. Also I prefer the visual difference between dashes and equal signs for headlines which is better to read than counting the number of hashes.

**Comment by sunn-e** [comment]
I just followed the markdown standards for GitHub. The number of hash defines the level of header. 1 hash defines it is highest level title and consecutively adjusting hash helps to keep track of level.
 # Biggest 
## Smaller
 ### Getting smaller
#### Much smaller 
##### and like wise

**Comment by sunn-e** [comment]
I was suggested to follow the same by OWASP mentors.

**Comment by behrisch** [comment]
Thank you for the request. I just included the badge and fixed some links. Our primary download location will change soon, so I did not include that but will keep it in mind. If you have more ideas for improvements please open a new request.

**Comment by sunn-e** [comment]
No problem @behrisch , thanks for informing. I'll send a new PR if something new comes to my mind.

**Pull request closed without merging**
