### PR TITLE
Fix the width of the internal bike lane connection

### LINKED ISSUE #10051: Fix the width of the internal bike lane connection in an intersection
The width of an internal lane is usually the one of the successor lane.

In some cases, if the predecessor is a bike lane and the successor is a normal lane, the width of the internal bike connection will be too large.

### PR DESCRIPTION
**Pull request by alexpagri**
Signed-off-by: Ioan-Alexandru Stef <alexstef34@yahoo.com>

Fixes #10051

### CODE REVIEW

**Comment by alexpagri** [comment]
I will prepare an update to the code.
In order to get everything right, I suggest getting the minimum width out of the predecessor/successor lane, at least for the bike lane, taking into account that bikes are now aligned rightmost on the sublane model.

**Comment by namdre** [comment]
@alexpagri I agree with using the minimum width.
Since the formula for determining width now spans several lines and is used more than once, please refactor it into a function.

**Comment by namdre** [comment]
The current state doesn't compile because of the extra `NBEdge::` 

I looked at the diffs (after fixing the build locally) and found one undesirable change:

In networks where the bike lanes have default width (`UNSPECIFIED_WIDTH`), the resulting internal lanes should also have default width. 
- With your PR, the .net.xml contains the attribute `width="3.20"` for these lanes 
- before the width (being set to UNSPECIFIED_WIDTH) wasn't written

This also introduces noise when evaluation the expected test outputs.

**Comment by namdre** [comment]
Thanks!

**Pull request merged**
