### PR TITLE
Add optional parking entry/exit times set by vType parameter

### PR DESCRIPTION
**Pull request by theDivj**
Signed-off-by: theDiv <div@thoda.uk>

Code to optionally allow more realistic parking space entry/exit timings (as-is enters/leaves space in a single sim step) meaning lanes are blocked for longer than a single step for parking, obscuring parking related congestion.

Timings are set by a vType parameter of the form:
manoeuverAngleTimes="10 3.0 4.0,80 1.1 11.0,110 11.0 2.0,170 8.0 2.5,181 3.0 4.0"

Each triplet in the parameter consists of an angle value followed by an entry-time and exit-time. The angles delimit ranges corresponding to the angle between the space and the lane.

In the example above a space that is angled between 0 and 10 degrees from the lane will block the lane for 3 seconds before entering the parking space and for 4 seconds on leaving the space.

(2nd submission reflecting comments on pull #5894)

### CODE REVIEW

**Comment by behrisch** [comment]
Thanks for the PR. We are currently preparing the next release (due on 20.8.) and will review it afterwards.

**Comment by theDivj** [comment]
Chortle - I had noticed major updates!
 - will keep aligned for now.
cheers

**Comment by namdre** [comment]
We updated some of the schema files and test results in the course of our release cycle. Can you resolve the merge conflict on your end, please?

**Comment by theDivj** [comment]
Of course, have been enjoying the updates to netedit - good stuff!

**Comment by theDivj** [comment]
conflict resolution

**Pull request closed without merging**
