### PR TITLE
Added parameter to setPreviousSpeed

### PR DESCRIPTION
**Pull request by Domsall**
I use setPreviousSpeed in scenarios in which a SUMO-vehicle is controlled by another program (another SUMO instance or a third-party program like Simulink).
When a program with higher timesteps forces a SUMO-vehicle to a specific speed (with setPreviousSpeed), the acceleration is calculated as if the vehicle had only changed the speed over its last timestep (but the other simulation changed the speed over a longer period with a lower decel/accel). The results are hard accelerating/braking maneuvers and create issues with the EIDM.
Therefore, I added the parameter "timefactor" to manipulate the acceleration calculation. Old behavior is timefactor=1.

Signed-off-by: Dominik Salles <dominik.salles@fkfs.de>

### CODE REVIEW

**Comment by namdre** [comment]
We have a strong policy against breaking backward compatibility. 
New parameter for existing methods should be optional 
- default argument in all clients to handle old scripts
- TraCI server code to handle old and new protocol version

Also, have you considered turning the extra parameter into 'acceleration'? rather than timefactor? The latter is more ambiguous whereas acceleration is more explicit.

**Comment by Domsall** [comment]
You are absolutely right. Sorry for the dirty pull request. I hope the changes reflect what you are looking for.
I also changed the parameter to 'acceleration' as you suggested.

**Comment by namdre** [comment]
Almost: TraCIServer will still complain when encountering an old client that only sends a 'speed' value. rather than 2 components.
Instead, it should handle both versions. For comparison, see how TraCIServerAPI_Vehicle::processSet handles VAR_EDGE_EFFORT

**Comment by namdre** [comment]
The code looks good now. I'm waiting for the tests to run and will then merge it.

**Pull request merged**
