### PR TITLE
Updated CACC by adding perception errors

### PR DESCRIPTION
**Pull request by mehdi-maleki**

### CODE REVIEW

**Comment by namdre** [comment]
@schwamborn concerning the discussion in #6330
- allowing driverstate for CACC seems to go against the model intention but there should be no technical reason against allowing this combination (might be construed as modelling sensor errors maybe)
- this PR would change the behavior of simulations that mix Krauss and CACC and set option **--device.driverstate.probability 1**. The inputs would have to be changed to specify driver state device by vType rather than with an option. Do you foresee a problem?

**Comment by behrisch** [comment]
@mehdi-maleki Thanks for this one! Unfortunately the required paperwork seems to be missing. Do you have an Eclipse account and accepted the ECA, see https://sumo.dlr.de/docs/FAQ.html#how_do_code_contributions_work ?

**Comment by schwamborn** [comment]
@namdre I generally agree with the first point. As you pointed out, however, it seems to go against the model's intention, which is why I would prefer driverstate to be opt-in and make the user switch it on explicitly (maybe separately via a CFModel parameter like `carFollowModel.caccApplyDriverState`).

**Comment by mehdi-maleki** [comment]
Hi,

Thanks for the update!

Yes, I have an Eclipse account and I signed the ECA (you can see in the
picture below).

@jakob if you mean driver awareness, yes I agree with you (since the
assumption is there is no driver in ACC and CACC). But in order to avoid
this problem when activating the driverstate device in CACC model, we
defined the initial awareness as 0.99 for the target vehicle. In this case,
we are able to introduce errors with the "Error State" parameter, which
allows us to model the sensor errors in speed and gap estimation.

Best regards,
Mehdi

[image: image.png]

**Comment by namdre** [comment]
driverstate is now applied for CACC model when activated by vType attribute `applyDriverState="1"`

**Comment by mehdi-maleki** [comment]
Great, thanks!

**Pull request closed without merging**
