### PR TITLE
correct lane access when importing from OSM

### PR DESCRIPTION
**Pull request by tinova-1**
I noticed, that lane accesses are not converted correctly (e.g. when there is a bus lane with the tag psv:lanes=yes|designated, this didn't get imported correctly. Now it should work as the user would expect. I wrote one test and edited one because of different behaviour now.
@behrisch This are only the code changes, not the comment typo fixes

### CODE REVIEW

**Comment by behrisch** [comment]
Thank you! Are the netgen tests expected to fail? Did you have a look at the ECA?

**Comment by tinova-1** [comment]
Yep, I did register for Eclipse and accepted the ECA. I even added a signoff to my commit. Some tests fail in the commit that I forked from. I was pretty sure that my edits don't fail any tests that succeed in the previous commit (4ce12b2a5d). But I'll check again.

**Comment by namdre** [comment]
@tinova-1 The eclipse website states that `Anonymous (webmaster@****.ch)` cannot be validated whereas `(timo@****.de)` is covered by the ECA. It seems as if some of your commits still have the wrong email.  You could try to copy all your changes into a fresh fork and do a single squashed PR with the validated email address.

**Comment by tinova-1** [comment]
I'm setting up a new fork anyway To Clean Up the Mess

**Comment by behrisch** [comment]
Thank you!

**Pull request closed without merging**
