### PR TITLE
Add support for fixed force off mode; initialize the phases by time in cycle

### PR DESCRIPTION
**Pull request by qichaow**
Add support for fixed force off (Issue #9848).
Initialized the phases by initial in-cycle time (which is affected by the offset and cycle length).

### CODE REVIEW

**Comment by namdre** [comment]
When I apply the diff  locally to the latest dev version, the NEMA controller no longer switches phases
 (https://patch-diff.githubusercontent.com/raw/eclipse/sumo/pull/9855.diff)

and I also get
```
src/microsim/traffic_lights/NEMAController.cpp:700:12: warning: unused variable ‘currentInCycleTime’ [-Wunused-variable]
     double currentInCycleTime = ModeCycle(currentTimeInSecond - cycleRefPoint - offset, myCycleLength);

```

**Comment by qichaow** [comment]
@namdre I tested the code locally and it was working. Can I get your latest dev version?

Qichao

**Comment by namdre** [comment]
I tested the patch against 1e954c64ad8b33c556f57aaf1635620254edae2a

**Comment by qichaow** [comment]
> I tested the patch against [1e954c6](https://github.com/eclipse/sumo/commit/1e954c64ad8b33c556f57aaf1635620254edae2a) Did you try your patch on a fresh clone from the main branch?

Yes, I fetched upstream in my fork. I will delete the fork and try it all over.

**Comment by behrisch** [comment]
I suppose this can be closed then

**Pull request closed without merging**
