### PR TITLE
Public Transport Tutorial Markdown, ref #8108

### PR DESCRIPTION
**Pull request by LaraKaiser**
Signed-off-by: Lara Kaiser <Lara.Kaiser@Student.HTW-Berlin.de>

A tutorial for: Public transport tutorial (without web wizard) #8108
Describes the useage of buses and trams within sumo and guides the user through a small exercise to build the first simulation utilizing public transports.

### CODE REVIEW

**Comment by namdre** [comment]
Some comments:
- add a link from the tutorials page (https://sumo.dlr.de/docs/Tutorials/index.html) to your new page 
- setting line="ANY" would create problems in bigger scenarios when different lines use the same stop. Thus it would be safer to set the line attribute of the trams and use that in the ride definition
- public transport typically drives according to a schedule (stop attribute 'until') and this is in fact a necessary condition for public transport routing (https://sumo.dlr.de/docs/Simulation/Public_Transport.html#public_transport_schedules) so I recommend adding this attribute as well in your tutorial

**Comment by LaraKaiser** [comment]
Thank you for your feedback! 
I added the link and set the line attributes accordingly. I also wrote another 
chaper for the schedules, to make it a little clearer.

**Comment by namdre** [comment]
lists require a leading empty line or they will not render correctly (e82deb4393f43b78fa24895d86bde26b9252ad3f)

**Comment by angelobanse** [comment]
To force a new line, you have to put three spaces (instead of `\`) at the end of the line.

**Pull request merged**
