### PR TITLE
add myReachedStrop attribute for Stage

### PR DESCRIPTION
**Pull request by tkchouaki**
This solved #6389 for me.

Regards.

### CODE REVIEW

**Comment by namdre** [comment]
I intend to merge this. However, since it does not solve all the issues of #6389 that I have in mind, it will take me a bit longer.

**Comment by namdre** [comment]
If you do not wish to fix the pull request after the heavy refactoring of my collegue, I can also integrate the changes manually as I wish to amend them anyway.

**Comment by tkchouaki** [comment]
Please proceed as you see fits better.

**Comment by behrisch** [comment]
I don't think it handles Stage_Trip correctly. @namdre Do we still plan to integrate it?

**Comment by namdre** [comment]
I plan to rewrite and amend this PR.

**Pull request closed without merging**
