### PR TITLE
[docs] Improved the SUMOlympics tutorial

### PR DESCRIPTION
**Pull request by bcoueraud87**

### CODE REVIEW

**Comment by m-kro** [comment]
Could you please unify the way you write netedit on this page? I spotted "NetEdit"...

**Comment by bcoueraud87** [comment]
@m-kro I don't see any in the new version, they are all written as netedit.

**Comment by m-kro** [comment]
Here: "We created the vehicle types and the vehicle flows "by hand", by writing the definitions down into a XML file, however these manipulations can directly be made (and visualized) in **NetEdit**!"

**Comment by bcoueraud87** [comment]
@m-kro You're right! I will make the change.

**Comment by bcoueraud87** [comment]
@m-kro Done!

**Pull request merged**
