### PR TITLE
MacrOutput

### PR DESCRIPTION
**Pull request by Amirhoseinkr73**
MacrOutput
This code which is called MacrOutput describes the relationship between density, flow, and speed based on sumo Edge-based output. Edge-base output includes some information about density, speed, travel time and etc. to extract fundamental diagrams based on Edge-based data, mean density, mean speed, and mean flow should be calculated. To calculate the mean of every component, data must be aggregated for all segments. In SUMO there is not any module to aggregate data and show fundamental diagrams. Also, aggregating data with some software like Excel is time-consuming. Therefore MacrOutput is developed to cover this gap. MacrOutput aggregate data and show macroscopic fundamental diagram (density vs flow, density vs speed, speed vs flow) based on simulation data. Also, MacrOutput demonstrates fundamental diagrams based on both density and lane density. Moreover, MacrOutput generates two output file which shows mean density, mean speed, mean flow results. The calculation process and relationships are taken from [1]. To use this feature execute the following steps:

      1.Put MacrOutput.py in the simulation folder.
      2.Run cmd
      3.Run this code (MacrOutput.py -i <input file (for example : OUTPUT_FILE.xml)>)

Reference

    [1]. Qiong Lu, Tamás Tettamanti, Dániel Hörcher & István Varga (2019): The impact of autonomous vehicles on urban traffic 
    network capacity: an experimental analysis by microscopic traffic simulation, Transportation Letters, DOI: 
    10.1080/19427867.2019.1662561.

Required packages
     pandas_read_xml
     pandas
     numpy
     collections
     matplotlib.pyplot

[MacrOutput.zip](https://github.com/eclipse/sumo/files/6623037/MacrOutput.zip)

### CODE REVIEW

**Comment by behrisch** [comment]
Thanks for the contirbution! Unfortunately it seems to be empty. Can you try again?

**Comment by Amirhoseinkr73** [comment]
Hello dear Michael, I have sent my file as MacrOutput.zip and I checked it, the file was okay. so what format do you think I should send the file to because here when I upload the Python file it does not allow it to be uploaded and does not support the Python format and I have to send it in zip format! Here is the text format of the code and zip file.

[MacrOutput.txt](https://github.com/eclipse/sumo/files/6704996/MacrOutput.txt)
[MacrOutput.zip](https://github.com/eclipse/sumo/files/6705006/MacrOutput.zip)

**Comment by behrisch** [comment]
Pull requests usually work by adding the modified files to a fork fo the repo but this did not seem to work out here. I can work with the attached files. Thank you.

**Comment by Amirhoseinkr73** [comment]
Thank you so much dear Michael, if it is necessary send your email here and I will send you a complete file with examples

**Comment by Amirhoseinkr73** [comment]
Hello dear Michael,
Did you see my code ?

**Comment by behrisch** [comment]
> Did you see my code ?

Yes, but it is summer holiday time ;-)

**Comment by Amirhoseinkr73** [comment]
Ohh you right ... Have a good summer 😊

**Comment by behrisch** [comment]
I finally integrated your script but still have a question:
Is this line correct: https://github.com/eclipse/sumo/blob/main/tools/visualization/macrOutput.py#L77 ?
It looks like you are overwriting the begin times

**Comment by Amirhoseinkr73** [comment]
Hi dear Michael,
thank you so much,
I checked it and the line of 73 is correct and the line of 70 can be removed.
also could you replace the line of 81 with this:
Length = df['sampledSeconds'] / (df['end']-df['begin']) / df['density']

**Comment by Amirhoseinkr73** [comment]
Hi dear Michael,
I checked the code with a network but I faced this error :
xml.parsers.expat.ExpatError: syntax error: line 1, column 0
I want to know how can we solve it and why you remove this part of code:

    from optparse import OptionParser
    optParser = OptionParser()
    optParser.add_option("-i", "--input", dest="input", metavar="FILE",
                         help="import the output file to use as input")

    # standard plot options
    helpers.addInteractionOptions(optParser)
    helpers.addPlotOptions(optParser)
    # parse
    options, remaining_args = optParser.parse_args(args=args)
In your opinion, it is not because of deleting this part of the code that we encounter an error؟

**Comment by behrisch** [comment]
You do not need to give **-i** any longer, just the file name

**Comment by Amirhoseinkr73** [comment]
Thank you so much dear Michael

**Comment by Amirhoseinkr73** [comment]
dear Michael, I am sorry to bother you. could you add this to the code:
#this code is based on Qiong Lu et al study.https://www.tandfonline.com/doi/full/10.1080/19427867.2019.1662561

**Pull request closed without merging**
