### PR TITLE
added sort GTFS output #8232

### PR DESCRIPTION
**Pull request by LaraKaiser**
The filter_trips method now calls sort_routes on the created route file.

Signed-off-by: LaraKaiser <Lara.Kaiser@Student.HTW-Berlin.de>

### CODE REVIEW

**Comment by behrisch** [comment]
Thanks for this one and sorry for the delay. Could you please recheck whether this also works with python2 and make the sorting optional?

**Comment by LaraKaiser** [comment]
Thank you for the feedback! I checked the code with Python2.7 and it worked fine. The user can now choose if the sorting should be included with the --sort option.

**Comment by behrisch** [comment]
Thanks! What is `os.path.join(os.getcwd(), ...` for? Looks like it should work without as well.

**Comment by behrisch** [comment]
Never mind I just merged it and we will do the cleanup afterwards

**Pull request merged**
