### PR TITLE
traci.person.setParameter("personId.stageIndex", "drivingStage.Lines"…

### PR DESCRIPTION
**Pull request by tkchouaki**
Hi,
I added the possibility to change the **lines** attribute of a driving stage online by using :

```python
traci.person.setParameter("personId.stageIndex", "drivingStage.Lines", "lines")
```

The given id should be composed of the id of the person & the concerned stage index.

Regards.

Signed-off-by: tarek chouaki <tarek.chouaki@irt-systemx.fr>

### CODE REVIEW

**Comment by behrisch** [comment]
Thank you for the request but I think I would rather not follow the path of adding a separate call for every parameter. Wouldn't it be better to let people retrieve the stage, modify it and send it back?

**Comment by tkchouaki** [comment]
The current API only allows appending a stage at the end of a person's plan.
Should the process be like this: 

- Retrieve the stage
- Remove it from the person's plan
- Modify the desired parameters
- Append the stage (so the APPEND_STAGE request should take also a stageIndex parameter)

Or maybe:

- Retrieve the stage
- Modify the desired parameters
- Replace it in the person's plan (by adding a REPLACE_STAGE request)

**Comment by behrisch** [comment]
I would prefer the second alternative.

**Comment by namdre** [comment]
I'm also in favor of adding a REPLACE_STAGE request

**Pull request closed without merging**
