### PR TITLE
Add metainfo.xml for to briefly describe the software

### PR DESCRIPTION
**Pull request by kevinsmia1939**
Add metainfo.xml for to briefly describe the software. Which is useful for software store like Flathub for example.
This is relate to this. https://github.com/eclipse/sumo/issues/9894

### CODE REVIEW

**Comment by behrisch** [comment]
Thanks for the patch! Could you please check whether you have an Eclipse account and have acknowledged the ECA, see https://github.com/eclipse/sumo/blob/main/CONTRIBUTING.md#eclipse-contributor-agreement

**Comment by behrisch** [comment]
@kevinsmia1939 We would love to include this in the next release. Can you manage to make the paperwork by the end of the week?

**Comment by kevinsmia1939** [comment]
not sure what I did, but the anonymous does not go away.

**Comment by behrisch** [comment]
OK, it seems this one get messed up but I am sufficently convinced that you did the paperwork but tthis got unmergeable now. Should I simply use the contents of this file: https://github.com/flathub/org.eclipse.sumo/blob/master/org.eclipse.sumo.metainfo.xml (which is more recent) and place it in  build/package/sumo.metainfo.xml ?

**Comment by kevinsmia1939** [comment]
> OK, it seems this PR got messed up but I am sufficently convinced that you did the paperwork. Should I simply use the contents of this file: https://github.com/flathub/org.eclipse.sumo/blob/master/org.eclipse.sumo.metainfo.xml (which is more recent) and place it in build/package/sumo.metainfo.xml ?

Yes, that is fine.

**Comment by behrisch** [comment]
OK, did that, thanks for the PR. So now after the next release we can update the flathub repo and remove the metainfo file there, correct?

**Comment by kevinsmia1939** [comment]
Yes we can, we can write a small command in the flatpak manifest to install the metainfo if it does not do it automatically.

**Pull request closed without merging**
