### PR TITLE
Improved Simple platoon manager2

### PR DESCRIPTION
**Pull request by schwoz**
**Improvement of platoonmanager**

Improvements are these:

1. before a vehicle starts following a leader, it checks if at least one of these conditions are satisfied:

- leader and ego vehicle have a certain number of edges in common on the future route

- leader and ego vehicle do a certain distance together on a future route

2. The lane change advice is not issued to a follower if it is less than a certain distance from the upstream intersection

Parameters are set on init:
- ego vehicle needs at least this number of future edges in common with leader before agreeing to follow...
        self._edgenumberLookahead = 3

- Or the ego vehicle needs at least this distance of commom route length with leader before agreeing to follow.
        self._distLookahead = 500.0

- no lane change advice if vehicle has less than this distance  to the next  junction
        self._lanechangeMinDist = 100.0

### CODE REVIEW

**Comment by schwoz** [comment]
Sorry I could not figure out how to be covered by the legal agreements. I looked at my eclipse account and I am a contributer but not a committer, which should be fine. I just agreed to the most recent license, don't know if that helps.

**Comment by namdre** [comment]
@behrisch any ideas what could be wrong here? Was the "signed-by" requirement or is it still needed?

**Comment by behrisch** [comment]
No, maybe wrong associated email or the github account is not present in the Eclipse account settings?

**Comment by behrisch** [comment]
@schwoz I also think this patch should be redone against the head of current main. Your fork seems to be severely out of date, that's why we have merge conflicts.

**Comment by schwoz** [comment]
My github email is identical to the eclipse email (I also did the git config --global user.email "email@example.com")
OK I have now merged the current sumo main with my master and resolved the conflict. Maybe it works now.

**Pull request closed without merging**
