### PR TITLE
SAGA added to the Contributed docs. 

### PR DESCRIPTION
**Pull request by lcodeca**

### CODE REVIEW

**Comment by lcodeca** [comment]
I cannot find a way to sign my commits from the GitHub interface.
I'm going to try again another time.

**Comment by behrisch** [comment]
It works for me, if I manually add an empty line and the signed-off footer in the commit description field.  But since you have commit rights anyway it is not that important.

**Comment by lcodeca** [comment]
I don't know why I cannot. You can see it happening in https://github.com/eclipse/sumo/pull/6435 too.
Apologies for this mess.

**Comment by behrisch** [comment]
My GitHub gives me "which email address associate with the commit" dialog field where you probably need to select a mail address fitting the signed off?

**Pull request closed without merging**
