### PR TITLE
Add some more information to OSMWebWizard.md

### PR DESCRIPTION
**Pull request by claell**
When going through the tutorial I cam across two more complicated points that were not mentioned, so I added them.

### CODE REVIEW

**Comment by behrisch** [comment]
SUMO_HOME should be set automatically. Which ubuntu package did you use?

**Comment by claell** [comment]
I used the one from the PPA as was found in the docs.

**Comment by claell** [comment]
Problem is maybe that I did not log out before invoking the script.

**Comment by behrisch** [comment]
So additions seem to be unnecessary, if not please reopen.

**Pull request closed without merging**
